[workspace]
resolver = "2"
members = ["crates/enoki2d", "crates/enoki2d_editor", "example"]

[patch.crates-io]
bevy = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_app = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_asset = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_camera = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_color = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_core_pipeline = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_derive = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_ecs = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_image = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_log = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_math = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_mesh = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_reflect = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_render = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_shader = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_sprite = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_sprite_render = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_tasks = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_time = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_transform = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_window = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_winit = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_input = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_ui = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_a11y = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_text = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_pbr = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_gizmos = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_picking = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_animation = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_audio = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_scene = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_state = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_diagnostic = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_internal = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_platform = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_ui_render = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_light = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_anti_alias = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_input_focus = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_post_process = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_utils = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_ptr = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_macro_utils = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_encase_derive = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }
bevy_gilrs = { git = "https://github.com/mirsella/bevy", branch = "release-0.17.3" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# This is used by trunk as it doesn't support custom profiles: https://github.com/trunk-rs/trunk/issues/605
# xbuild also uses this profile for building android AABs because I couldn't find a configuration for it
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
